spring:
  application:
    name: redis-news-portal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=news-portal
    username: postgres
    password: andreymstepanov
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      generate-ddl: true
      #spring.jpa.generate-ddl - это vendor-INdependent аналог spring.jpa.hibernate.ddl-auto
      defer-datasource-initialization: false
#      properties:
      javax:
          persistence:
            schema-generation:
              database:
                action: none
      hibernate:
          ddl-auto: create-drop
#          hbm2dll:
#            create_namespaces: true
            #spring.jpa.hibernate.ddl-auto is actually a Spring Boot shortcut for the "hibernate.hbm2ddl.auto" property.
            #Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none"
          show_sql: true
          format_sql: true
          connection:
            autocommit: false
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
          temp:
            use_jdbc_metadata_defaults: false


#spring.datasource.initialization-mode (S B 2) и spring.sql.init.mode ( SB 3) в значении always аналогичны higher-level Database Migration Tool, like Flyway or Liquibase
# т.е. формируют структуру базы при старте приложения из скриптов schema.sql  и data.sql
#  datasource:
#    initialization-mode: always

  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog-master.yml
    database-change-log-lock-table: news_portal_databasechangeloglock
    database-change-log-table: news_portal_databasechangelog

logging:
  file:
    name: logs/redis-news-portal.log