CREATE TABLE IF NOT EXISTS article (
	id int8 NOT NULL,
	content varchar(1024) NOT NULL,
	CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comment (
	id int8 NOT NULL,
	content varchar(255) NULL,
	rating int8 NULL,
	article_id int8 NOT NULL,
	CONSTRAINT comment_pkey PRIMARY KEY (id)
);

ALTER TABLE comment ADD CONSTRAINT comment_article FOREIGN KEY (article_id) REFERENCES article(id);

CREATE SEQUENCE  IF NOT EXISTS ARTICLE_CUSTOM_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE  IF NOT EXISTS COMMENT_CUSTOM_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;